from gym.envs.registration import register

register(
    id='subt-tunnel-v0',
    entry_point='gym_subt.envs:SubtTunnelEnv',
)
register(
    id='subt-urban-v0',
    entry_point='gym_subt.envs:SubtUrbanEnv',
)
register(
    id='subt-tunnel-linear-v0',
    entry_point='gym_subt.envs:SubtTunnelLinearEnv'
)
register(
    id='subt-tunnel-allaction-v0',
    entry_point='gym_subt.envs:SubtTunnelAllactionEnv'
)
register(
    id='subt-tunnel-front-v0',
    entry_point='gym_subt.envs:SubtTunnelFrontEnv'
)
register(
    id='subt-cave-allaction-v0',
    entry_point='gym_subt.envs:SubtCaveAllactionEnv'
)
register(
    id='subt-cave-goal-v0',
    entry_point='gym_subt.envs:SubtCaveGoalEnv'
)
register(
    id='subt-cave-rnn-v0',
    entry_point='gym_subt.envs:SubtCaveRnnEnv'
)
register(
    id='subt-cave-dense-v0',
    entry_point='gym_subt.envs:SubtCaveDenseEnv'
)
register(
    id='subt-cave-baseline-v0',
    entry_point='gym_subt.envs:SubtCaveBaselineEnv'
)
register(
    id='subt-cave-noback-v0',
    entry_point='gym_subt.envs:SubtCaveNobackEnv'
)
register(
    id='subt-cave-3d-v0',
    entry_point='gym_subt.envs:SubtCave3DEnv'
)
register(
    id='subt-cave-forward-discrete-v0',
    entry_point='gym_subt.envs:SubtCaveForwardDiscreteEnv'
)
register(
    id='subt-cave-forward-goal-v0',
    entry_point='gym_subt.envs:SubtCaveForwardGoalEnv'
)
register(
    id='subt-cave-forward-v0',
    entry_point='gym_subt.envs:SubtCaveForwardEnv'
)
